// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5kpjwVl7iPt5Z68LrBpMNvpIFPo4PJ8k',
    appId: '1:669237339982:web:2cfbcf5c8f1f858f37201f',
    messagingSenderId: '669237339982',
    projectId: 'flutter-firebase-dersler-e4561',
    authDomain: 'flutter-firebase-dersler-e4561.firebaseapp.com',
    storageBucket: 'flutter-firebase-dersler-e4561.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT0wpd1YDwkKjsRe6xk0uFmHSRdMq266c',
    appId: '1:669237339982:android:b6c2545ee0a59b1637201f',
    messagingSenderId: '669237339982',
    projectId: 'flutter-firebase-dersler-e4561',
    storageBucket: 'flutter-firebase-dersler-e4561.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxPP_fl05NXa4JNyrvnTX3AGE1H1Af3DA',
    appId: '1:669237339982:ios:e1a88e6965d48b9b37201f',
    messagingSenderId: '669237339982',
    projectId: 'flutter-firebase-dersler-e4561',
    storageBucket: 'flutter-firebase-dersler-e4561.appspot.com',
    iosClientId: '669237339982-7jovund0qpdoeipfjhs6r59b4vkcppnl.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxPP_fl05NXa4JNyrvnTX3AGE1H1Af3DA',
    appId: '1:669237339982:ios:e1a88e6965d48b9b37201f',
    messagingSenderId: '669237339982',
    projectId: 'flutter-firebase-dersler-e4561',
    storageBucket: 'flutter-firebase-dersler-e4561.appspot.com',
    iosClientId: '669237339982-7jovund0qpdoeipfjhs6r59b4vkcppnl.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
